name: test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Julia
    - name: Set up Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: '1.10'  # You can specify any Julia version you need

    # Step 3: Install dependencies (optional but recommended)
    - name: Install dependencies
      run: |
        julia --project=. -e 'import Pkg; Pkg.instantiate()'

    # Step 4: Run tests
    - name: Run tests
      run: |
        julia --project=. test/runtests.jl
